### ISSUE TITLE
border이 overflow에 영향을 미치는 현상

### ISSUE THREAD

**Issue by milkbottle0305** [khu-bigdata-project-team-5/client#9]
```
export const LectureItem = styled(Lecture)`
  cursor: pointer;
  border: ${(props) =>
    props.selected ? "0.25rem solid #4B3BFF" : "0.25rem solid transparent"};
`;
```
border none을 주면 selected 상태일때 아이템이 흔들리는 현상이 있어 transparnet로 값을 주었음.

<img width="387" alt="image" src="https://github.com/khu-bigdata-project-team-5/client/assets/52454255/1c794284-2d4c-4cbd-bf78-1a40df9f229f">
<img width="356" alt="image" src="https://github.com/khu-bigdata-project-team-5/client/assets/52454255/1d3335e8-6b26-45ed-8561-10d5fb71d6a6">

하지만, border 이 존재하면 0.25rem씩 양쪽에 총 0.5rem씩 아이템 width가 늘어나서 overflow가 되어 스크롤이 되는 현상

**Comment by rlaminseok0824** [comment]
nice solution

**Comment by milkbottle0305** [comment]
```box-sizing: border-box```로 border까지 width, height로 크기를 취급하는 속성으로 해결하였습니다.
